
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["POSTGRESQL_MAX_CONNECTIONS"] || 5 %>
  
development:
  adapter: postgresql
  encoding: unicode
  database: 'saas-dev'
  username: 'saas'
  password: 'saas'
  host: '127.0.0.1'
  port: 5432
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: 'saas-test'
  username: 'saas'
  password: 'saas'
  host: '127.0.0.1'
  port: 5432
  pool: 5
